workflows:
  ios-automatic-code-signing:
    name: iOS automatic code signing
    instance_type: mac_mini_m2
    
    environment:
      groups:
        - appstore_credentials
      xcode: 16.2
      cocoapods: default
      
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fset up provisioning profiles
        script: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo ${CM_PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
          echo "Saved provisioning profile $PROFILE_PATH"
      - name: Add signing certificate to keychain
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password 123456
      - name: Install pods
        script: |
          cd WordComboBunny
          pod install --repo-update --verbose
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --verbose
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --workspace "WordComboBunny/WordComboBunny.xcworkspace" --scheme "WordComboBunny" --config Release --verbose
          
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect: # https://docs.codemagic.io/publishing-yaml/distribution
        submit_to_app_store: true
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY # Contents of the API key
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER # Alphanumeric value that identifies the API key
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Alphanumeric value that identifies who created the API key
      email:
        recipients:
          - "zakaranrayon@icloud.com"
        notify:
          success: true
          failure: true
